server:
  port: 8084

spring:
  application:
    name: catalog-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalogdb

# --- Configuraci√≥n de Eureka ---
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      # URL de tu Eureka Server
      defaultZone: http://localhost:8761/eureka/